### ISSUE TITLE
Question 145

### ISSUE THREAD

**Issue by kryanecs** [Ditectrev/AWS-Certified-Solutions-Architect-Associate-SAA-C03-Practice-Tests-Exams-Questions-Answers#10]
Answer should be C. Better answer is to allow KMS to handle the the signed certs

**Comment by danieldanielecki** [comment]
Correct. Fixed in https://github.com/Ditectrev/AWS-Certified-Solutions-Architect-Associate-SAA-C03-Practice-Tests-Exams-Questions-Answers/commit/afdb76dd025295f63d6a8ed090bf115e3eb2e4c8.
