### ISSUE TITLE
Question 160

### ISSUE THREAD

**Issue by kryanecs** [Ditectrev/AWS-Certified-Solutions-Architect-Associate-SAA-C03-Practice-Tests-Exams-Questions-Answers#11]
Answert should be 4 
Would use VPC with private (DB) and public (WEB) subnets:
http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_VPC.Scenarios.html
Multi AZ requirement forces me to multiply subnets by two.
Reasons:
For DB: Your VPC must have at least one subnet in at least two of the Availability Zones in
the region where you want to deploy your DB instance. A subnet is a segment of a VPC’s IP
address range that you can specify and that lets you group instances based on your security
and operational needs
http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_VPC.WorkingWithRDSIns
tanceinaVPC.html
For Web: After creating a VPC, you can add one or more subnets in each Availability Zone.
Each subnet must reside entirely within one Availability Zone and cannot span zones
http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Subnets.html

**Comment by GatienBoquet** [comment]
#16 fixed.

**Comment by danieldanielecki** [comment]
> #16 fixed.

Hence, closing.
