### ISSUE TITLE
question 207 missing part of the question

### ISSUE THREAD

**Issue by kryanecs** [Ditectrev/AWS-Certified-Solutions-Architect-Associate-SAA-C03-Practice-Tests-Exams-Questions-Answers#14]
it should be A government client needs you to set up secure cryptographic key storage for some of their extremely confidential data. You decide that the AWS CloudHSM is the best service for this. However, there seem to be a few pre-requisites before this can happen, one of those being a security group that has certain ports open. Which of the following is correct in regards to those security groups?

**Comment by GatienBoquet** [comment]
Fix #16

**Comment by danieldanielecki** [comment]
> Fix #16

Hence, closing.
