### ISSUE TITLE
Question 208 missing

### ISSUE THREAD

**Issue by kryanecs** [Ditectrev/AWS-Certified-Solutions-Architect-Associate-SAA-C03-Practice-Tests-Exams-Questions-Answers#15]
You forgot to add A web company is looking to implement an intrusion detection and prevention system into their deployed VPC. This platform should have the ability to scale to thousands of instances running inside of the VPC

**Comment by danieldanielecki** [comment]
@kryanecs can you please create a PR for all your findings?

**Comment by GatienBoquet** [comment]
Fixed in #16

**Comment by danieldanielecki** [comment]
> Fixed in #16

Hence, closing.
