### ISSUE TITLE
Wrong answer for question 226

### ISSUE THREAD

**Issue by DHoussama** [Ditectrev/AWS-Certified-Solutions-Architect-Associate-SAA-C03-Practice-Tests-Exams-Questions-Answers#2]
Is there a method in the IAM system to allow or deny access to a specific instance?
The correct answer is yes
https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_evaluation-logic.html#policy-eval-denyallow

**Comment by danieldanielecki** [comment]
Thanks, fixed in https://github.com/Ditectrev/AWS-Certified-Solutions-Architect-Associate-SAA-C03-Practice-Tests-Exams-Questions-Answers/commit/5e33b7e55e989c0cc20ade26ccb560b639cce4c9
