### ISSUE TITLE
Remove duplicates

### ISSUE THREAD

**Issue by danieldanielecki** [Ditectrev/AWS-Certified-Solutions-Architect-Associate-SAA-C03-Practice-Tests-Exams-Questions-Answers#22]
The questions contain few duplicated questions, clearly visible with [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) Visual Studio Code extension.

<img width="1244" alt="Screenshot 2024-05-09 at 20 04 58" src="https://github.com/Ditectrev/AWS-Certified-Solutions-Architect-Associate-SAA-C03-Practice-Tests-Exams-Questions-Answers/assets/12736263/9d12594d-ee95-4cfb-adce-fb6383e5474f">

**Comment by GatienBoquet** [comment]
Will work on this on another PR to keep it clean.

**Comment by GatienBoquet** [comment]
fixed on #28

**Comment by danieldanielecki** [comment]
closed in #28 indeed, last changes to be verified during generation of contents with `DocToc`, then duplicated links would have `-1)`. Keeping it open by then

**Comment by danieldanielecki** [comment]
+ review last formatting from #19

**Comment by danieldanielecki** [comment]
Fixed in https://github.com/Ditectrev/AWS-Certified-Solutions-Architect-Associate-SAA-C03-Practice-Tests-Exams-Questions-Answers/commit/256653d3f865588b0d555b3d647230f25ee9de18, almost ready for v2.0.0, just table of contents!
