### ISSUE TITLE
Question 67 incorrect

### ISSUE THREAD

**Issue by kelmryan** [Ditectrev/AWS-Certified-Solutions-Architect-Associate-SAA-C03-Practice-Tests-Exams-Questions-Answers#25]
Answer should be ` -[ ] A Route payment requests through two NAT instances setup for High Availability and whitelist the Elastic IP addresses attached to the MAT instances`

**Comment by GatienBoquet** [comment]
#28

**Comment by danieldanielecki** [comment]
Thanks, so we can close this one!
