### ISSUE TITLE
Question 75 is incorrect.

### ISSUE THREAD

**Issue by kelmryan** [Ditectrev/AWS-Certified-Solutions-Architect-Associate-SAA-C03-Practice-Tests-Exams-Questions-Answers#26]
Answer should be - [x] Assign an IAM role to the Amazon EC2 instance.

**Comment by GatienBoquet** [comment]
#28

**Comment by danieldanielecki** [comment]
@GatienBoquet fixed it in #28, so no longer necessary to create PR. Closing this issue then.
