### ISSUE TITLE
Question 6 might be incorrect

### ISSUE THREAD

**Issue by dani0854** [Ditectrev/AWS-Certified-Solutions-Architect-Associate-SAA-C03-Practice-Tests-Exams-Questions-Answers#29]
According to documentation:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html#ConsistencyModel

_Amazon S3 provides strong read-after-write consistency for PUT and DELETE requests of objects in your Amazon S3 bucket in all AWS Regions. This behavior applies to both writes to new objects as well as PUT requests that overwrite existing objects and DELETE requests._

I think they changed it in 2020 from eventual consistency. Thought I might be missing some catch in "any type" of first answer.

**Comment by danieldanielecki** [comment]
I've checked it with Bing's Copilot, and it says the answers are correct. If you think the `eventual consistency` should be replaced, then please submit a Pull Request (PR), because I have no opinion ;-)
