### ISSUE TITLE
Question 34 can be removed

### ISSUE THREAD

**Issue by kuchtek** [Ditectrev/AWS-Certified-Solutions-Architect-Associate-SAA-C03-Practice-Tests-Exams-Questions-Answers#37]
Quite an old one:
https://aws.amazon.com/about-aws/whats-new/2014/05/19/amazon-rds-for-sqlserver-introduces-multi-az-support/
```
Multi-AZ deployment [...] supported for Microsoft SQL Server DB Instances.
```

**Comment by danieldanielecki** [comment]
Based on https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_SQLServerMultiAZ.html & https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_SQLServer.html it looks like it's still relevant.
