### ISSUE TITLE
Wrong Answer on Question 8?

### ISSUE THREAD

**Issue by avpcirelliSNJ** [Ditectrev/AWS-Certified-Solutions-Architect-Associate-SAA-C03-Practice-Tests-Exams-Questions-Answers#41]
**Because of the extensibility limitations of striped storage attached to Windows Server, Amazon RDS does not currently support increasing storage on a [...] DB Instance.**

I couldn't find anything to confirm the answer. (SQL-SERVER).
Could you give me the reference for the affirmation?

**Comment by danieldanielecki** [comment]
@avpcirelliSNJ it looks like `If you use production online transaction processing (OLTP) workloads.` is indeed the correct answer.

Might you please submit a Pull Request (PR)?

**Comment by danieldanielecki** [comment]
Fixed in https://github.com/Ditectrev/AWS-Certified-Solutions-Architect-Associate-SAA-C03-Practice-Tests-Exams-Questions-Answers/commit/2e7196f9eac20196e71a41663071c1b100d9b1a6.
